"""
Django settings for lms project.

Generated by 'django-admin startproject' using Django 5.2.13.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY
SECRET_KEY = 'django-insecure-vz5&_)17wlbwn3##qv@_m)w9(#0uub-q+lq)no3mieg)irp3x^'
DEBUG = True
ALLOWED_HOSTS = []


# APPLICATIONS
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'accounts',
    'dashboard',
    'captcha',
    'courses',
    'assignments',
    'progress',
    'notifications',
    'enrollments',
    'channels',
    'teams',
    'attendance',
    'ai_chat',
    'settings',
    'certificates',
    'coding_tasks',
    
]

# Custom user model
AUTH_USER_MODEL = 'accounts.User'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}



from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'en'

USE_I18N = True

LANGUAGES = [
    ('en', 'English'),
    ('hi', 'Hindi'),
    ('te', 'Telugu'),
    ('kn', 'Kannada'),
    ('ml', 'Malayalam'),
    ('ur', 'Urdu'),
    ('ta', 'Tamil'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    # IMPORTANT FOR LANGUAGE SWITCH
    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ROOT URL
ROOT_URLCONF = 'lms.urls'

RAZORPAY_KEY_ID = "rzp_test_SlwV9Vy26UoaY6"
RAZORPAY_KEY_SECRET = "VKNQeiPnBuL82ZCdrrnnYVq7"

# RAZORPAY_KEY_ID = "rzp_live_xxxxx"
# RAZORPAY_KEY_SECRET = "xxxxxxxx"

# RAZORPAY_WEBHOOK_SECRET = "whsec_xxxxx"

# # IMPORTANT for prod
# DEBUG = False
# ALLOWED_HOSTS = ["E-learing.com"]

# CSRF_TRUSTED_ORIGINS = ["https://E-learing.com"]

# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# WSGI
WSGI_APPLICATION = 'lms.wsgi.application'
ASGI_APPLICATION = "lms.asgi.application"
GEMINI_API_KEY = "AIzaSyA8j5dfLgPnJZygG-Urlo5gMWrOEm6WedE"

# DATABASE
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# INTERNATIONALIZATION
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# STATIC FILES
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# MEDIA FILES
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# DEFAULT PRIMARY KEY
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# AUTHENTICATION REDIRECTS ✅ IMPORTANT FIX
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/attendance/student/'
LOGOUT_REDIRECT_URL = '/login/'