# Generated by Django 6.0.4 on 2026-05-06 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_courses_user_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
