# Generated by Django 6.0.5 on 2026-05-08 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_tasks', '0001_initial'),
        ('courses', '0012_remove_liveclass_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingsubmission',
            old_name='code',
            new_name='submitted_code',
        ),
        migrations.RemoveField(
            model_name='codingsubmission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='codingtask',
            name='language',
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='codingtask',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coding_tasks', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingtask',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='codingtask',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingtask',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingtask',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
