# Generated by Django 6.0.4 on 2026-05-08 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('fingerprint_login', models.BooleanField(default=False)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('autoplay_videos', models.BooleanField(default=True)),
                ('offline_downloads', models.BooleanField(default=False)),
                ('allow_chat', models.BooleanField(default=True)),
                ('allow_discussions', models.BooleanField(default=True)),
                ('live_class_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
