# Generated by Django 6.0.4 on 2026-05-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('ur', 'Urdu'), ('bn', 'Bengali'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('pa', 'Punjabi'), ('or', 'Odia')], default='en', max_length=10),
        ),
    ]
