# Generated by Django 6.0.4 on 2026-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_usersettings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
