# Generated by Django 6.0.4 on 2026-05-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_usersettings_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
