# Generated by Django 6.0.4 on 2026-04-26 14:48

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_topic_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='material',
            field=models.FileField(blank=True, null=True, upload_to='materials/', validators=[courses.models.validate_1tb_file_size]),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', validators=[courses.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[courses.models.validate_1tb_file_size]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='topics/pdfs/', validators=[courses.models.validate_1tb_file_size]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='topics/thumbnails/', validators=[courses.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='topics/videos/', validators=[courses.models.validate_1tb_file_size]),
        ),
    ]
