# Generated by Django 6.0.4 on 2026-04-26 15:45

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_price_alter_topic_course_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='demo_videos/', validators=[courses.models.validate_1tb_file_size]),
        ),
    ]
