# Generated by Django 6.0.4 on 2026-04-27 03:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_liveclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='meeting_link',
        ),
        migrations.AddField(
            model_name='liveclass',
            name='room_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
