# Generated by Django 6.0.4 on 2026-05-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_liveclass_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveClass',
        ),
    ]
