# Generated by Django 6.0.4 on 2026-05-07 14:09

import courses.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_delete_liveclass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student_photo', models.ImageField(blank=True, help_text='Director/Principal photo shown on certificate', null=True, upload_to='certificate_director/', validators=[courses.models.validate_image_size])),
                ('director_signature', models.ImageField(blank=True, help_text='Director signature shown on certificate', null=True, upload_to='certificate_signatures/', validators=[courses.models.validate_image_size])),
                ('director_name', models.CharField(blank=True, default='', help_text="Director's name shown below signature on certificate", max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
