# Generated by Django 6.0.4 on 2026-05-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_course_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
