# Generated by Django 6.0.5 on 2026-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30, verbose_name='Time in seconds'),
            preserve_default=False,
        ),
    ]
