# Generated by Django 6.0.4 on 2026-05-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_question_time_limit'),
        ('courses', '0016_delete_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.topic'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
