# Generated by Django 6.0.4 on 2026-05-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment', 'Payment'), ('assignment_submitted', 'Assignment Submitted'), ('assignment_review', 'Assignment Review'), ('message', 'Message'), ('progress', 'Progress'), ('enrollment', 'Enrollment'), ('course', 'Course'), ('meeting', 'Meeting'), ('admin', 'Admin')], max_length=50),
        ),
    ]
