# Generated by Django 6.0.4 on 2026-05-07 04:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_locationlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationlog',
            old_name='timestamp',
            new_name='tracked_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_faces/'),
        ),
        migrations.AddField(
            model_name='break',
            name='total_break_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='break',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendance'),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
